apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: collector
type: Opaque
stringData:
  DATABASE_URL: "postgresql://<user>:<password>@postgres:5432/<db>"
  ZITADEL_CLIENT_SECRET: "client-secret"
