apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: collector
type: Opaque
stringData:
  POSTGRES_PASSWORD: "collectorPassword"
  POSTGRES_USER: "collectorAdmin"
  POSTGRES_DB: "collectorDB"
