apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: collector

resources:
  - ../../base
  - ../../observability
  - ingress.yaml

  # ZITADEL inside Minikube (separate DB)
  - zitadel/postgres.yaml
  - zitadel/secret.example.yaml
  - zitadel/deployment.yaml
  - zitadel/ingress.yaml

patches:
  - path: patch-api-configmap.yaml
  - path: patch-api-migrate-job.yaml
  - path: patch-front-configmap.yaml
  - path: patch-imagepullpolicy.yaml
