apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: collector
data:
  NEXT_PUBLIC_API_URL: "https://collector.local/api"
  NEXTAUTH_URL: "https://collector.local"
  ZITADEL_ISSUER: "https://zitadel.collector.local"
  ZITADEL_INTERNAL_ISSUER: "http://zitadel:8080"
  ZITADEL_CLIENT_ID: "replace-me-zitadel-client-id"
  ZITADEL_POST_LOGOUT_URL: "https://collector.local/api/auth/logout/callback"
