apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: collector

resources:
  - namespace.yaml

  - postgres/secret.example.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml

  - api/configmap.yaml
  - api/secret.example.yaml
  - api/service.yaml
  - api/deployment.yaml
  - api/migrate-job.yaml

  - frontend/configmap.yaml
  - frontend/secret.example.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
