apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - zitadel/postgres.yaml
  - zitadel/deployment.yaml
  - api/configmap.yaml
  - api/service.yaml
  - api/deployment.yaml
  - frontend/configmap.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
  - ingress/ingress.yaml
  - zitadel/ingress.yaml
