global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: collector-api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:3001']

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

  - job_name: promtail
    metrics_path: /metrics
    static_configs:
      - targets: ['promtail:9080']

