apiVersion: v1
kind: Secret
metadata:
  name: collector-tls
  namespace: collector
type: kubernetes.io/tls
stringData:
  tls.crt: |
    REPLACE_WITH_GENERATED_CERT
  tls.key: |
    REPLACE_WITH_GENERATED_KEY
