apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-api
spec:
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: Always
---
apiVersion: batch/v1
kind: Job
metadata:
  name: collector-api-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-front
spec:
  template:
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
